### PR TITLE
google_geocoder.go: Handle case with ZERO_RESULTS

### PR DESCRIPTION
**Pull request by MartinThoma**
This is a fix for issue #32

### CODE REVIEW

**Comment by MartinThoma** [comment]
@pedromorgan I've just changed it to return an error (nil for string is not allowed, so I return an empty string).

**Comment by kellydunn** [comment]
Good catch, @pedromorgan .  I should probably include a `errcheck` test run to verify things like this on travis.

**Comment by MartinThoma** [comment]
@kellydunn Thank you! Sorry, I cannot make the other change suggested by @pedromorgan. Could you please merge it and make the change?

**Comment by kellydunn** [comment]
for those following along with this PR, the change was introduced in:  5f721a7

**Pull request merged**
