### PR TITLE
add MarshalBinary/UnmarshalBinary such that gob.encode works for point

### PR DESCRIPTION
**Pull request by djk121**
Hi,

This enables gob encode/decode, https://golang.org/pkg/encoding/#BinaryMarshaler for details.

Thanks,
Dan

### CODE REVIEW

**Comment by kellydunn** [comment]
Heya @djk121 !  And thanks for the Pull Request!

It looks like your changes didn't make it through CI; it appears they error out here:

```
$ go test
# github.com/kellydunn/golang-geo
./point.go:131: undefined: binary
./point.go:135: undefined: binary
./point.go:147: undefined: binary
./point.go:153: undefined: binary
```

Looks like you might need to import the `binary` package in `point.go`?

**Comment by djk121** [comment]
Oops, sorry about that.  Fixed up now.

**Comment by kellydunn** [comment]
looks great!  merging now :)

Thanks for your work, @djk121 !

**Comment by djk121** [comment]
Cool, thanks!

**Pull request merged**
